services:

  generator:
    build:
      context: ./generator
      dockerfile: Dockerfile
    image: generator
    container_name: generator
    ports:
      - "8000:8000"
    volumes:
      - ./generator/logs:/app/logs
      - ./generator/stats:/app/stats

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    stop_grace_period: 20s

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 5s
      retries: 12

  fluent-bit:
      image: fluent/fluent-bit:4.2.0
      volumes:
        - ./fluent-bit:/fluent-bit/etc
        - ./generator/logs:/app/logs
      depends_on:
          kafka:
            condition: service_healthy

  logstash:
    build:
      context: ./logstash
    image: logstash
    ports:
      - "9600:9600"
    #volumes:
    #  - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - kafka
      - clickhouse

  clickhouse:
    image: clickhouse/clickhouse-server:25.9.5-alpine
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    ports:
      - "8123:8123"
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
      - clickhouse_data:/var/lib/clickhouse
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query 'SELECT 1' || exit 1"]
      interval: 5s
      retries: 10
      start_period: 20s

  grafana:
    build:
      context: ./grafana
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse


  kafka-monitor:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: kafka-monitor
    command: ["bash", "/kafka-throughput-monitor.sh"]
    volumes:
      - ./kafka-throughput-monitor.sh:/kafka-throughput-monitor.sh:ro
    depends_on:
      - kafka
    networks:
      - default

  clickhouse-monitor:
    build:
      context: ./clickhouse-monitor
      dockerfile: Dockerfile
    container_name: clickhouse-monitor
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: unless-stopped

volumes:
  clickhouse_data: